### ISSUE TITLE
Script code

### ISSUE THREAD

**Issue by degloff** [localizely/flutter-intl-intellij#10]
Currently it is not possible to specify the script code appropriately, like Chinese simplified zh_Hans_CN. How can that be done?

**Comment by aleksakrstic** [comment]
Hi @degloff 

Currently script code is not supported.
Usually `zh_CN` is enough for Chinese simplified.

Mainland China (`zh_CN`) & Singapore (`zh_SG`) both use simplified characters, and Taiwan (`zh_TW`) & Hong Kong (`zh_HK`) use traditional characters. 
Since China and Taiwan are the two with the biggest populations, just `zh_CN` and `zh_TW` are often used to distinguish the simplified and traditional character versions.

Additional info: https://stackoverflow.com/a/4894634/12453836

Will that solution work in your case?

**Comment by degloff** [comment]
Thanks a lot. Though this does not follow the Flutter standard it is good enough.

**Comment by degloff** [comment]
Hm actually there is still a problem with Flutter and iOS. It looks like that Flutter on iOS does not pick up the. proper version of Chinese (traditional vs simplified), see also here https://github.com/flutter/flutter/issues/22642. 

If I query the preferred device languages on iOS with Flutter (region set to US), I get

```
flutter: zh-Hant-US
flutter: zh-Hans-US
```
to Flutter. 

I have defined zh_CH (with simplfied) and zh_TW (with traditional translation) in the flutter project and added it also to the plist.info file the same way. 

Flutter then always chooses the traditional, regardless of the iOS system language (Chinese Simplfied vs Traditional). Probably we have to be able to add zh_Hans and zh_Hant with the plugin?

**Comment by degloff** [comment]
I made further tests on iOS. If I add by hand the following locale

```
      Locale.fromSubtags(languageCode: 'zh', scriptCode: 'Hans', countryCode: 'CN'),
      Locale.fromSubtags(languageCode: 'zh', scriptCode: 'Hant', countryCode: 'TW'),
```

to `S.supportedLocales` in the generated `I10n.dart` and create the corresponding `messages_zh_Hans_CN.dart`, `messages_zh_Hant_TW.dart`. Then we can correctly resolve simplified versus traditional. Adding this capability should not be a big deal to the plugin. 

Given the large Chinese market it would be worth an update.

**Comment by degloff** [comment]
Actually after having changed some of the files the plugin cannot recognize any locales anymore. I have to set up everything again from scratch.

**Comment by goranluledzija** [comment]
Hi @degloff 
Thanks for the input!
Will leave this issue open for adding support for `scriptCode` in upcoming plugin updates.

**Comment by goranluledzija** [comment]
Hi @degloff 
Support for `scriptCode` is not available with the new version `1.4.0` of the plugin.

**Comment by qcdys** [comment]
> 实际上，在更改了某些文件后，插件不再能够识别任何语言环境。我必须重新设置所有内容。

Is your switch working? There's still something wrong with mine.

**Comment by aleksakrstic** [comment]
Hi @qcdys 
Could you give us more info about the issue you face?
