### ISSUE TITLE
Disable auto generation on save

### ISSUE THREAD

**Issue by xVemu** [localizely/flutter-intl-intellij#102]
Is it possible to disable auto generation of intl files, after saving a `.arb` file?

**Comment by lzoran** [comment]
Setting `enabled` to `false` under the `flutter_intl` section of the `pubspec.yaml` file should disable the Flutter Intl plugin, and therefore the auto-generation.

The `pubspec.yaml` file:
```yaml
flutter_intl:
  enabled: false
```

**Comment by xVemu** [comment]
Works perfectly, thank you!
