### ISSUE TITLE
Error: The class 'FileSystemEvent' can't be extended, implemented, or mixed in outside of its library because it's a sealed class.

### ISSUE THREAD

**Issue by sonphamtrung17** [localizely/flutter-intl-intellij#103]
I upgrade flutter version 3.13. When I put new value in arb file, plugin generate error with message:

Failed to build intl_utils:generate:
../../.pub-cache/hosted/pub.dev/watcher-1.0.2/lib/src/constructable_file_system_event.dart:7:57: Error: The class 'FileSystemEvent' can't be extended, implemented, or mixed in outside of its library because it's a sealed class.
abstract class _ConstructableFileSystemEvent implements FileSystemEvent {
                                                        ^
Process finished with exit code 1

Please help me check issue, many thanks 😊 

<details><summary>Flutter doctor</summary>
<p>
[✓] Flutter (Channel stable, 3.13.0, on macOS 13.4.1 22F770820d darwin-x64, locale en-VN)

    • Flutter version 3.13.0 on channel stable at /Users/sonpham/Dev/flutter_version/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision efbf63d9c6 (7 days ago), 2023-08-15 21:05:06 -0500
    • Engine revision 1ac611c64e
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/sonpham/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • ANDROID_HOME = /Users/sonpham/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • macOS (desktop)              • macos         • darwin-x64     • macOS 13.4.1 22F770820d darwin-x64
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 116.0.5845.96

[✓] Network resources
    • All expected network resources are available.

• No issues found!
</p>
</details>

**Comment by lzoran** [comment]
Hi @SonPham17,

I believe that this problem is somehow related to an issue with the cache that occurs after a Flutter upgrade.

What version of the `intl_utils` package do you use?
```
flutter pub global list
```

Could you check if reactivating the intl_utils package helps?
```
flutter pub global deactivate intl_utils
flutter pub global activate intl_utils
```

**Comment by sonphamtrung17** [comment]
> 
`flutter pub global deactivate intl_utils`
`flutter pub global activate intl_utils`

It worked for me! Thank you 🙏
