### ISSUE TITLE
How to split the intl_en.arb file into multiple files when there is a lot of data。

### ISSUE THREAD

**Issue by Min-King** [localizely/flutter-intl-intellij#104]
Now I have a problem
The intl_en.arb file has reached over a thousand lines of code and I want to split this file.
![2501692779507_ pic](https://github.com/localizely/flutter-intl-intellij/assets/30712512/325914be-a816-4f60-8023-3eecb632caf8)

My pubsec.yaml file in configuration is like this
![2511692779522_ pic](https://github.com/localizely/flutter-intl-intellij/assets/30712512/35e223a3-eb15-45c2-af28-124d037c7532)

What can I do,
I really hope to get your help.

**Comment by lzoran** [comment]
Hi @Min-King,

Thanks for sharing this concern.

Currently, that feature isn't available in the Flutter Intl plugin.
I noticed there's [another issue](https://github.com/localizely/flutter-intl-intellij/issues/6) discussing the same, so I'll close this for a more organized tracking.

**Comment by Min-King** [comment]
Hi @lzoran ，
Thank you for your answer.
