### ISSUE TITLE
How to customize class names and add multiple localizationsDelegates within a project

### ISSUE THREAD

**Issue by ZhongGuanbin** [localizely/flutter-intl-intellij#107]
Hello, Thank you for this plugin.
It's an amazingly convenient plugin that automates almost everything I need to do for localization.
I'm struggling now because I want to create multiple localizationsDelegates in a project and differentiate them by customizing different names.
Since this feature not being found in the plugin,  I would like to make a feature request.
Thank you very much again for this plugin, and we look forward to the launch of these two features.

**Comment by lzoran** [comment]
Hi @ZhongGuanbin,

Thank you very much for your contribution!

It seems that there is an [existing issue](https://github.com/localizely/flutter-intl-intellij/issues/22) that touches on the topic of adding multiple localization delegates. Could you please check if your feature request is in line with that discussion?

**Comment by ZhongGuanbin** [comment]
来信获悉，感谢您的支持！耑此奉复                                                                           钟冠彬This is an automatic reply, confirming that your e-mail was received.Thank you

**Comment by ZhongGuanbin** [comment]
Hi @lzoran 

Thank you very much for your reply.

I have read through the [existing issue](https://github.com/localizely/flutter-intl-intellij/issues/22) you provided and i'm trying to use  https://github.com/Innim/flutter_multiple_localization to load and override messages
