### ISSUE TITLE
Wrong translation when generating custom select

### ISSUE THREAD

**Issue by EdwynZN** [localizely/flutter-intl-intellij#14]
I added a custom select (not gender) to my arb files

en
`
"Types": "{choice, select, Figure {Figure} Card {Card} Yarn {Yarn} other {Other}}",
`
es
`
"Types": "{choice, select, Figure {Figura} Card {Tarjeta} Yarn {Lana} other {Otro}}",
`

and it generates the correct messages in messages_en.dart and message_es.dart

`static m6(choice) => "${Intl.select(choice, {'Figure': 'Figure', 'Card': 'Card', 'Yarn': 'Yarn', 'other': 'Other', })}";`

but in i10n.dart it generates int.message instead of Intl.select and retrieve an incorrect message, retrieving all the conditions
```

String Types(dynamic choice) {
    return Intl.message(
      '{choice, select, Figure {Figure} Card {Card} Yarn {Yarn} other {Other}}',
      name: 'Types',
      desc: '',
      args: [choice],
    );
  }
```

when I use print(S.of<context>.Types('Figure')); the output is 
`{type, select, Figure {Figure} Card {Card} Yarn {Yarn} other {Other}}`

if I manually edit i10n.dart the problem is solved but I shouldn't modify it by hand

```
String Types(dynamic choice) {
    return Intl.select(
      choice,
      {'Figure': 'Figure', 'Card': 'Card', 'Yarn': 'Yarn', 'other': 'Other', },
      name: 'Types',
      args: [choice]
    );
  }

print(S.of<context>.Types('Figure')); 
Output: Figure
```
Is this a bug or am I writting something wrong in the ARB file? 

Reading the intl.dart the select method comment say that it can receive enum and it will truncate the toString() method which I was planning to use to pass some enums and translate them depending the language

EDIT: Also it displays this message when generating the files
`WARNING: The 'Types' key has an unsupported content type.`
I don't know if I should add some resource attributes or what to change. The only available examples are with gender and they really didn't help to understand the whole syntax

**Comment by aleksakrstic** [comment]
Hi @EdwynZN 
Custom selects are not supported at the moment, but we plan to support it in one of upcoming plugin updates.

Thanks for reporting this, so others can upvote the issue and helps us prioritize the work.

**Comment by aleksakrstic** [comment]
@EdwynZN 
Custom selects are now supported with new plugin version `1.5.0`
