### ISSUE TITLE
Setup instructions setup MaterialApp.localizationsDelegates incorrectly

### ISSUE THREAD

**Issue by maguro** [localizely/flutter-intl-intellij#16]
It needs to also add `GlobalMaterialLocalizations`, etc.:

          localizationsDelegates: [
            S.delegate,
            GlobalMaterialLocalizations.delegate,
            GlobalWidgetsLocalizations.delegate,
            GlobalCupertinoLocalizations.delegate,
          ],

**Comment by aleksakrstic** [comment]
@maguro 
Documentation updated.
Thanks for the input.
