### ISSUE TITLE
Get text resource by key and index

### ISSUE THREAD

**Issue by totalerex** [localizely/flutter-intl-intellij#18]
Two possible use cases is described here.

Sometimes key of the text resource is coming from outside in string format (in json for example). 

How to: 
1. Lookup if it is exists in text resources.
2. Get it from text resources by string key as it is defined in ARB files. 
Something like:` S.of(context).sByKey("SOME_STRING_KEY")`.

Sometimes may be useful if get resource by index (it is not like existing plurals functionality).
So, would be nice to have defined keys in ARB file:
```
 "myKey0" : "aaa", 
"myKey1" : "bbb",
"myKey2": "ccc",
....
"myKey100" : "xyz",
```

and access them by index - `S.of(context).myKey(2)`.

Thank you!

**Comment by aleksakrstic** [comment]
Hi @yoavrofe
Those translations that you want to fetch from the outside of the app (assume using REST API or similar), will they contain the same keys as ARB files contain that are inside the app code?
Or you will fetch translations with completely new keys that are not known during the app build?

Regarding key getters by index:
Unfortunately this will diverge from official practices for Flutter internationalization.
If official `intl` and `intl_translation` libraries start supporting something like that, we would gladly support it with the plugin as well.

**Comment by totalerex** [comment]
ok, let's forget index getters.

Regarding first point, yes translations and keys should be already in ARB, the keys themselves are fetched from outside and application just displays correct strings to user according keys received from server. Nothing to fetch during runtime :) BTW I just thought that "like index" getters may work this way also. So access resources by string key may be really useful feature.

**Comment by aleksakrstic** [comment]
@totalerex 
I wouldn't do it that way, since it would diverge from official localization practices for Flutter.
I guess your issue would be solved once `select` type of translations are supported with the plugin?

There is already created an issue for that: https://github.com/localizely/flutter-intl-intellij/issues/14

**Comment by aleksakrstic** [comment]
@totalerex  
Custom selects are now supported with new plugin version `1.5.0`

**Comment by kirimi** [comment]
Hi! @totalerex

I have a similar case. 
In my case one Markdown string contains the key of other string. 

For instance footnote links:
```json
"mdtext": "markdown example [link1](footnote1) and [link2](footnote2)",
"footnote1": "This is the text of the footnote.",
"footnote2": "This is the text of the footnote2."
```

So, after taping the link, I have the key of a footnote's string.

In order to get the translation of footnotes, I use the extension:

```dart
import 'package:intl/intl.dart';
import 'package:myapp/generated/l10n.dart';

extension SExtensions on S {
  String byKey(String key, {List<Object> args}) => Intl.message('', name: key, desc: '', args: args);
}
```

and access them by key:

```dart
S.of(context).byKey('footnote1');
```

@aleksakrstic
It will be great to have a built-in mechanism like:

```dart
S.of(context).byKey('key');
S.of(context).hasKey('key');
```

**Comment by aleksakrstic** [comment]
Hi @kirimi 
I believe you can use "select" forms for that as well.
Key-value example:

    "pageHomeWelcomeRole": "{role, select, admin {Hi admin!} manager {Hi manager!} other {Hi visitor!}}"

More info on plugin page: https://plugins.jetbrains.com/plugin/13666-flutter-intl
