### ISSUE TITLE
String extractor from Dart code

### ISSUE THREAD

**Issue by goranluledzija** [localizely/flutter-intl-intellij#2]
When I have a string literal in Dart code, 
I would like to have an option to automatically add a new key to ARB files and to replace it with key getter in the code.

**Comment by d-silveira** [comment]
the [plugin I was using previously,](https://plugins.jetbrains.com/plugin/10128-flutter-i18n) until it got deprecated, did this!
It must be easy to port that part of the code from it, no?

**Comment by aleksakrstic** [comment]
Hi @d-silveira 
We planned this feature for upcoming plugin update.
Rough estimate for the update is 5th March.

**Comment by aleksakrstic** [comment]
This feature is now released with plugin version `1.3.0`.

Extract string to ARB files using [intention action](https://www.jetbrains.com/help/idea/intention-actions.html). The dialog will ask you to confirm string key and value, and also to select existing locales to which given string will be extracted.
