### ISSUE TITLE
_notInlinedMessages() should be updated

### ISSUE THREAD

**Issue by maguro** [localizely/flutter-intl-intellij#21]
The `_notInlinedMessages()` static function  should be defied as:

    static Map<String, Function> _notInlinedMessages(_) => {

It seems that Dart 2.8 cannot decipher the return type from the map literal and so it must be explicitly declared.  With that said, I don't understand why the code doesn't directly assign the map literal to `messages`:

    final messages = {

**Comment by aleksakrstic** [comment]
Hi @maguro 
I just tried with Flutter version `1.17.0` & Dart version `2.8.0-dev.18.0`, and I don't see any issue with that line of code.

However, those `messages_*.dart` files are generated by `intl_translation` library on which the plugin relies under the hood. Hence we don't have direct impact on the generated code.

**Comment by maguro** [comment]
That specific line has no error.  It's the line above it that has the error
> `A value of type 'dynamic' can’t be assigned to a variable of type 'Map<String, dynamic>'.`

Thanks for the pointer.  I'll file a ticket in the other project.

**Comment by hw20101101** [comment]
> Map<String, Function>


good
