### ISSUE TITLE
Strings are displayed very short in default language each time the app is restarted

### ISSUE THREAD

**Issue by DFelten** [localizely/flutter-intl-intellij#25]
Thanks for this plugin. I love how easy it is to add translations. It works great, but I noticed a problem.

The strings are displayed for a short time (Just for a tenth of a second) in the default language each time the app is restarted. The texts are then output correctly in the device language.

The problem is probably that the app is built once and only then the language is adjusted and the MaterialApp is built again with the new language.

My MaterialApp 
```
return MaterialApp(
  builder: ExtendedNavigator<Router>(router: Router()),
  localizationsDelegates: [
    S.delegate,
    GlobalMaterialLocalizations.delegate,
    GlobalCupertinoLocalizations.delegate,
    GlobalWidgetsLocalizations.delegate,
    DefaultCupertinoLocalizations.delegate,
  ],
  supportedLocales: S.delegate.supportedLocales,
);
```

**Comment by aleksakrstic** [comment]
Hi @DFelten 
Usually this does not happen.
Do you maybe somewhere in the code call `S.load(...)` that changes locale on the app start? Like inside the router?
If you don't find solution there, maybe you can try it by defining `localeListResolutionCallback` for the `MaterialApp`.

**Comment by DFelten** [comment]
Thanks for the answer, I will try. I'm using `S.load()` for changing the language in the settings, but only there and just when the user manually select the language.
