### ISSUE TITLE
How to handle interpolation

### ISSUE THREAD

**Issue by BizzottoClaudio** [localizely/flutter-intl-intellij#28]
I am not sure how to use the interpolation with the generated get method. How can i pass my variables? I can't find the documentation of it, altough intl supports interpolation.

**Comment by aleksakrstic** [comment]
Hi @BizzottoClaudio 
If you want to use placeholders with your translations, you can wrap them in curly brackets inside Arb files.
Arb file:

    "pageHomeWelcomeFullName": "Welcome {lastName} {firstName}"

After that, in Dart code you can use it this way:

    S.of(context).pageHomeWelcomeFullName("John", "Doe")

More info about placeholders usage, plural and other format you can find in plugin documentation: https://plugins.jetbrains.com/plugin/13666-flutter-intl
