### ISSUE TITLE
Add examples for skeleton

### ISSUE THREAD

**Issue by alvinvin00** [localizely/flutter-intl-intellij#33]
I'm lost on how to make a String plural and other stuff, please add some docs to illustrate how to use plural and other stuff

**Comment by aleksakrstic** [comment]
Hi @alvinvin00 
Did you have a chance to check `pageNotificationsCount` key example on IDE plugin doc https://plugins.jetbrains.com/plugin/13666-flutter-intl , or `pageHomeSamplePlural` key from our sample project https://github.com/localizely/flutter-intl-plugin-sample-app/blob/master/lib/l10n/intl_en.arb ?

Or you missed something else, like better documentation on ICU format that is used for plural, etc?

**Comment by alvinvin00** [comment]
i missed the example on Jetbrains Plugin page while VS Marketplace has the tutorial, and yeah a separate docs would be great :)

**Comment by alvinvin00** [comment]
Well, my bad, actually JetBrains page has it too, closing this issue since that's on me
