### ISSUE TITLE
The getters of all keys are not defined for the type 'S'.

### ISSUE THREAD

**Issue by SIJH** [localizely/flutter-intl-intellij#34]
For example, I defined a key login in arb files. When I tried to use it with S.of(context).login, it failed with a warning that The getter 'login' isn't defined for the type 'S'.

**Comment by aleksakrstic** [comment]
Hi @SIJH 
Can you confirm you have following in your `pubspec.yaml` file:

    flutter_intl:
        enabled: true

When you save changes you made in arb file, the IDE runs code generation and opens "Messages" tool where it prints errors if they happen. Do you see something useful there? Could be arb file is not valid json or similar

If that didn't help, could you share your (part of) arb file where `login` string key is defined?

**Comment by SIJH** [comment]
Hi @aleksakrstic 

Thank you very much for your instant reply.

Yes, I confirm that flutter_intl is enabled in the pubspec.yaml file.

I did not see any errors messages printed.

For intl_en.arb
{
  "login": "Login",
  "@login": {
    "type": "text",
    "placeholders": {}
  },
}

For intl_zh_Hans.arb
{
  "login": "登录",
  "@login": {
    "type": "text",
    "placeholders": {}
  },
}

I checked the process over and over again. 

Thank you again.

**Comment by aleksakrstic** [comment]
Hi @SIJH 
If you have only that one string key in given arb files, then the last comma (,) in both of them is excessive and makes it invalid json file.

Also I assume your file is in the following folder: `lib/l10n/`

**Comment by SIJH** [comment]
Hi @aleksakrstic 
It is just an example string key, but not the last one. I checked there is no comma behind the last string key. Yes, the arb files are located in lib/l10n/. All dart files are generated properly in generated/ fold.

**Comment by aleksakrstic** [comment]
Hi @SIJH 
Could it be that `login` string key is not defined in your main locale defined inside `pubspec.yaml`?
String keys list is concluded from the main locale ARB file.

**Comment by SIJH** [comment]
Hi @aleksakrstic,

I don't think so. It does not work for any string keys defined in the arb files.

I will build a test project to see what goes wrong bout my current project.  I will keep you updated.

Thank you very much.
