### ISSUE TITLE
Android studio cannot find the Plugin

### ISSUE THREAD

**Issue by ShengjieGeng** [localizely/flutter-intl-intellij#35]
![image](https://user-images.githubusercontent.com/18364968/88636503-9c83d980-d0eb-11ea-8674-a50d47149fd8.png)
please help.
thanks anyway！

**Comment by aleksakrstic** [comment]
Hi @ShengjieGeng 
When searching by "flutter" keyword you should see a bunch of different plugins listed.
Apparently something is wrong with your IDE configuration, its proxy of plugins marketplace url.

Anyway, you can always install plugin manually:
- Download from: https://plugins.jetbrains.com/plugin/13666-flutter-intl/versions
- Install from the disk: https://www.jetbrains.com/help/idea/managing-plugins.html#install_plugin_from_disk
