### ISSUE TITLE
Support null safety

### ISSUE THREAD

**Issue by innwin** [localizely/flutter-intl-intellij#36]
Thank you for this nice plugin. 
Our app use null safety. can support null safety? 
Thank you !

**Comment by emiliodallatorre** [comment]
Hi,
I'm having the same problem @innwin.
Is it planned to start supporting null safety?

**Comment by lzoran** [comment]
Hi @innwin, @emiliodallatorre,

Thanks for reporting this!
We have in plan to support null safety.
Unfortunately, we are blocked at the moment with the `intl_translation` package, which we are using for localization files generation. We will have to wait until they support it.

**Comment by emiliodallatorre** [comment]
That's great, I'm happy to hear!

**Comment by TomKrauss** [comment]
Still no null safety support for the intl_translation package. Would it be possible - as a work around until you may officially support null safety - generate the messages_all.dart and the i10n.dart files with a 

// @dart = 2.7 

directive in the header?

**Comment by aleksakrstic** [comment]
The main discussion about null-safety support is here https://github.com/localizely/intl_utils/issues/14 since that is the core package under the hood.

Will use this issue for IDE plugin migration after `intl_utils` migration.

**Comment by aleksakrstic** [comment]
Hi everyone,
IDE plugin version 1.13.0 is released.
Supports null-safety and uses intl_utils 2.1.0 under the hood.
