### ISSUE TITLE
can not remove the "en" locale.

### ISSUE THREAD

**Issue by aprz512** [localizely/flutter-intl-intellij#37]
Remove Exisiting Locale

if i choose en, this plugin seems not work as ecpected.

it generate intl_en.arb file again.

**Comment by lzoran** [comment]
Hi @aprz512,

Flutter Intl plugin requires the existence of the main locale.
By default, the main locale is `en`.
To remove `en` locale from the project, you should ensure that the `main_locale` is updated within the `flutter_intl` configuration (`pubspec.yaml` file).

```
...
flutter_intl:
  enabled: true
  main_locale: en # Optional. Sets the main locale used for generating localization files. Provided value should consist of language code and optional script and country codes separated with underscore (e.g. 'en', 'en_GB', 'zh_Hans', 'zh_Hans_CN'). Default: en
...
```

More info regarding plugin configuration you can find [here](https://plugins.jetbrains.com/plugin/13666-flutter-intl) under **General Usage Instructions - Configuration options**.

**Comment by aprz512** [comment]
@lzoran 

thanks
