### ISSUE TITLE
Using S.of(context).appName to configure the MaterialApp title attribute to error。

### ISSUE THREAD

**Issue by guominfang** [localizely/flutter-intl-intellij#38]
![image](https://user-images.githubusercontent.com/24568042/91213045-a0833580-e743-11ea-9e14-6c80e7e4970d.png)

**Comment by masseelch** [comment]
use the `onGenerateTitle` property of the `MaterialApp`. It gives you a context you can call `S.of(context)`.

```
MaterialApp(
  onGenerateTitle: (context) => S.of(context).title,
  [...]
)
```
