### ISSUE TITLE
Only one language gets loaded

### ISSUE THREAD

**Issue by masseelch** [localizely/flutter-intl-intellij#39]
No matter what i do, i cannot get any other language to load than the one set in the config as `main_locale`.

```
flutter_intl:
  enabled: true
  main_locale: de
```
This will always only load the german files. Even if the english locale gets set. If its set to `en` the german language wont load.

What am i doing wrong?

```
MaterialApp(
        navigatorKey: _navigatorKey,
        routes: _routes,
        localizationsDelegates: [
          T.delegate,
          GlobalMaterialLocalizations.delegate,
          GlobalWidgetsLocalizations.delegate,
        ],
        supportedLocales: widget.supportedLocales,
      )
```

```
Text(S.of(context).title) // Will always return the language of main_locale.
```

**Comment by aleksakrstic** [comment]
Hi @masseelch 
Make sure you set `localizationDelegates`, `supportedLocales`... configuration as described here https://plugins.jetbrains.com/plugin/13666-flutter-intl  

How do you test loading of different locales? Did you test by changing locales supported on your test device OS, to those you have supported in your app? 
Those will be tried to match the first, otherwise it chooses the main locale.

**Comment by masseelch** [comment]
Hi @aleksakrstic, thanks for the fast reply.

I followed the configuration as described. 

To test different locales i simply added only the locale to test to the `supportedLocales` array. Did one build with `Locale.fromSubtags(languageCode: 'de')` and one with `Locale.fromSubtags(languageCode: 'en')`. Both times only the language for the locale configured in `pubspec.yaml` loaded.

**Comment by aleksakrstic** [comment]
@masseelch 
Why do you test it that way?

I think you should always set `supportedLocales: S.delegate.supportedLocales` as described in plugin documentation, and test different languages by changing languages on Operating System, or by changing it inside the app with `S.load(Locale('de', 'DE'))`
