### ISSUE TITLE
Reference the translation without context

### ISSUE THREAD

**Issue by goranluledzija** [localizely/flutter-intl-intellij#4]
As a developer
when I want to reference the key translation in Dart code
I want to have an option to do it without passing `context`

Example: `S.current.hello` this is very handy when I don't have a context and don't want to pass it 5 levels down just for localization.

**Comment by bogdanmarinescu** [comment]
I think you can attach a key to any widget and then use it anywhere in your methods
`_myKey = GlobalKey();`

` void _printkey() >= print(S.of(_myKey.currentContext).hello);`

**Comment by FatihAydin52** [comment]
+1

**Comment by talatkuyuk** [comment]
I also need this feature since I have a dart file consists some constant literals for pupup menu choises, and there is no context in that file.

**Comment by aleksakrstic** [comment]
Seems this becomes important.
We will give it a higher priority.
Thanks you for voting!

**Comment by DFelten** [comment]
This would be a great improvement.

**Comment by kunibertgangnam** [comment]
We need this ! Please add the feature as soon as possible. I just moved from i18n, as it seems to randomly crash the app, but having to have the BuildContext for localization is just not always possible without breaking the pattern you use.

**Comment by vsxed** [comment]
Any update on this?

**Comment by aleksakrstic** [comment]
This is in testing phase.
Should be available on Monday or Tuesday next week, due to longer plugin approval period from JetBrains.

**Comment by talatkuyuk** [comment]
Could it be possible for also VS Code? Actually I use VS Code nowadays, and
I need this feature for VS Code.

Many thanks for your effort, it is really appreciated.

**Comment by aleksakrstic** [comment]
@talatkuyuk Yes, it will be supported in VS Code next week as well.

For now you can use it with CLI tool `intl_utils:1.6.0`: https://pub.dev/packages/intl_utils

**Comment by aleksakrstic** [comment]
This is now available in version `1.8.0`.

You can access the keys without passing `context`, for example:

    S.current.title

**Comment by talatkuyuk** [comment]
I will try and provide feedback, many thanks...

8 Haz 2020 Pzt, saat 17:31 tarihinde Aleksa Krstic <notifications@github.com>
şunu yazdı:

**Comment by DerDave** [comment]
Hi... Can anybody tell me how I can use this in dart code?
I also need this in my viewmodels, but have no idea how. 

So far I used: AppLocalizations.of(context)

Thanks a lot

(sorry if this was a stupid question)
