### ISSUE TITLE
Add extension method to access translations

### ISSUE THREAD

**Issue by KlausJokinen** [localizely/flutter-intl-intellij#40]
Would it be possible to add an extension method to access translation.

Implementation
```
extension TranslationExtension on BuildContext {
  SS get S => Localizations.of<SS>(this, SS);
}
```

Usage
`context.S.boardingPageTitle`

We can of course do this on our own, but I would prefer it to be within `l10n.dart` file.

**Comment by aleksakrstic** [comment]
Hi @KlausJokinen 
Thanks for the suggestion.
Seems it might be confusing for users how to use translation getters if there are multiple ways to use it.
I prefer to stick to current solution if there is no additional demand for that in upcoming days.
Of course, you can always customize it for your projects with that extension method.
