### ISSUE TITLE
Could not find a file named "pubspec.yaml" in "intl_utils-1.6.5".

### ISSUE THREAD

**Issue by DhavalRKansara** [localizely/flutter-intl-intellij#41]
Using the [Flutter Intl](https://plugins.jetbrains.com/plugin/13666-flutter-intl) facing the below error and it will not be generating localizable strings in the i10.dart file.

```
/Users/dhavalkansara/flutter/bin/flutter --no-color pub global run intl_utils:generate
Waiting for another flutter command to release the startup lock...
Could not find a file named "pubspec.yaml" in "/Users/dhavalkansara/.pub-cache/hosted/pub.dartlang.org/intl_utils-1.6.5".
pub finished with exit code 66
Process finished with exit code 66
```

**Comment by lzoran** [comment]
Hi @DhavalRKansara,

Thanks for reporting this!

I've tried to reproduce this issue, but without success. Everything works well on my machine.
I guess this problem has something with pub cache. 🤔 
Could you try to deactivate `intl_utils` manually, and after that to trigger localization files generation (maybe it can help).

Steps:
1. Deactivate `intl_utils`
```
flutter pub global deactivate intl_utils
```

2. Update one of ARB files and press `Ctrl + S`

**Comment by Syaba999** [comment]
> Hi @DhavalRKansara,
> 
> Thanks for reporting this!
> 
> I've tried to reproduce this issue, but without success. Everything works well on my machine.
> I guess this problem has something with pub cache. 🤔
> Could you try to deactivate `intl_utils` manually, and after that to trigger localization files generation (maybe it can help).
> 
> Steps:
> 
> 1. Deactivate `intl_utils`
> 
> ```
> flutter pub global deactivate intl_utils
> ```
> 
> 1. Update one of ARB files and press `Ctrl + S`


Thanks, its works for me
