### ISSUE TITLE
Incompatible with AS 4.1

### ISSUE THREAD

**Issue by bakua** [localizely/flutter-intl-intellij#42]
Hello, I've updated Android studio to the lates 4.1 version and now I cannot install the plugin even manually. Says it's incompatible with the current Intellij version.

**Comment by lzoran** [comment]
Hi @bakua,

First of all, thank you for raising an issue and helping us to improve the Flutter Intl plugin.

I've tried to reproduce the reported issue with the latest Android Studio (version 4.1), and everything works well.
Maybe restarting Android Studio IDE or uninstalling and installing Flutter and Dart plugins may help, not sure. 😕

**Comment by bakua** [comment]
Hello, yes doing a clean setup fixed it for me. Thanks :)
