### ISSUE TITLE
. IOS /Flutter/ flutterport_environment.sh: line 8: Line: Inherited: Command Not Found

### ISSUE THREAD

**Issue by zhumj** [localizely/flutter-intl-intellij#44]
I have integrated the Flutter module into my iOS project, and if my Flutter used this plugin, I will get an error when Compiled in Xcode: ". IOS /Flutter/ flutterport_environment.sh: line 8: Line: Inherited: Command Not Found ".

**Comment by aleksakrstic** [comment]
Hi @zhumj,

It does not look related to this plugin. Maybe related to Flutter SDK configuration for the project?
Could you share more info, what is in that file on line 8 and similar?

**Comment by zhumj** [comment]
我把 pubspec.yaml 里面的
```
flutter_intl:
  enabled: true
  class_name: S
  main_locale: en
```
这段配置注释掉之后再进行编译就能编译成功。

**Comment by aleksakrstic** [comment]
@zhumj I found some similar issues at flutter repo https://github.com/flutter/flutter/issues/63176 https://github.com/flutter/flutter/issues/63552
Or you could try to run the working sample project https://github.com/localizely/flutter-intl-plugin-sample-app and see if that happens there as well?

**Comment by zhumj** [comment]
I think their problems are different from mine.
