### ISSUE TITLE
Regarding the release time of the "simultaneous support for multiple localizations" function

### ISSUE THREAD

**Issue by hanandjun** [localizely/flutter-intl-intellij#45]
Find a similar issue on the [flutter official website](https://github.com/flutter/flutter/issues/28456#issuecomment-498608580)，
Note that related issues have been mentioned in the issues.[related issues](https://github.com/localizely/flutter-intl-intellij/issues/26), 
and the discussion time for this issue is in July, now it’s mid-November, may I ask you roughly When can this feature be released? Thank you, do you have any temporary suggestions for amendments to the current situation.
Thank you very much for your work

**Comment by aleksakrstic** [comment]
Hi @hanandjun 
I answered here https://github.com/localizely/flutter-intl-intellij/issues/26.
Lets use that former issue for this topic.
