### ISSUE TITLE
Custom select with keys having spaces

### ISSUE THREAD

**Issue by absar** [localizely/flutter-intl-intellij#47]
I am using custom select, however in my scenario I need to pass **"select"** keys with spaces in some scenarios, unfortunately the parser doesn't like it. While I can workaround it by using strings without spaces e.g. **IncomeOther** however it will create additional boilerplate in calling widgets for scenarios where the string is not in the translation file, then **"other"** will return the provided string without space **IncomeOther** instead of **Income Other**, other workaround will be to return empty string from **"other"** however that will also require additional boilerplate on widget side to show original string.
#### Example arb file:
{
"transactionCategory": "{transactionCategory, select, Expenses {Expenses} **Income Other** {Income Other} other {{transactionCategory}}}"
}

Above will throw error:
ERROR: The 'transactionCategory' key will be ignored due to parsing errors.

However if the parser is updated to support custom **"select"** keys having strings with spaces with the help of quotes it will really help out
{
"transactionCategory": "{transactionCategory, select, Expenses {Expenses} **'Income Other'** {Income Other} other {{transactionCategory}}}"
}

**Comment by aleksakrstic** [comment]
Hi @absar 
This could diverge from ICU syntax for selects, so I think we can not support it.

Not sure how do you get "Income Other" value in that form as an argument for the string getter, but I would prefer to use enums anyway, that do not have whitespaces, or that use underscores (eg `income_other`). 
If that is not possible, I think boilerplate would be minimal if using `transactionCategory.replaceAll(' ', '')` when passing the value.
Hope I gave some alternative ideas.
