### ISSUE TITLE
plugin is incompatible with this installation android studio (4.1.1)

### ISSUE THREAD

**Issue by sahmadreza** [localizely/flutter-intl-intellij#49]
I can not install plugin in android studio 4.1.1 !

[https://imgur.com/6Pn3MPg](url)

**Comment by aleksakrstic** [comment]
Hi @sahmadreza 
I just tried to install Flutter Intl plugin on Android Studio 4.1.1 and everything is fine.

Could you give more info about the issue you have?
Is it that Flutter Intl plugin is not visible inside Android Studio when you try to search for it, or you can find it but fails to install or something else?

**Comment by sahmadreza** [comment]
Hi,
This problem was related to Android Studio itself and the problem was solved by cleaning the cache android studio !

Thanks :)
