### ISSUE TITLE
Cannot initialize plugin

### ISSUE THREAD

**Issue by dreampowder** [localizely/flutter-intl-intellij#5]
I cannot activate the plugin because the links for "Initialize for the Project" command is not working and i cannot see the command either.

**Comment by dreampowder** [comment]
ok i have found the command after scrolling through the documentation. but please make the anchor links working . 
btw thanks for this wonderful tool

**Comment by aleksakrstic** [comment]
Hi @dreampowder 
Thanks for pointing it out.

Unfortunately hash links are not available for description on given plugin page, so I just updated it to be more clear.
