### ISSUE TITLE
Add Doco

### ISSUE THREAD

**Issue by drekka** [localizely/flutter-intl-intellij#51]
Please add a decent readme or something. I can see comments in the releases about this option or that option, but there's nothing telling me how to configure those options? Where? how? values for them? what is the effect?

**Comment by aleksakrstic** [comment]
Hi @drekka 
Did you check plugin's official page https://plugins.jetbrains.com/plugin/13666-flutter-intl ?
We update the documentation regularly there, under "General Usage Instructions" section. 
Under "Configuration options" there are mentioned all configuration options. 
Did we miss something?
