### ISSUE TITLE
Dart Analysis picks up always_declare_return_types lint in generated messages_.. files

### ISSUE THREAD

**Issue by absar** [localizely/flutter-intl-intellij#54]
Hi,
Dart Analysis picks up always_declare_return_types lint rules in generated **messages_..** files, which adds unnecessary analysis issues when using Pedantic rules. Can we either add a **dynamic** return type or ignore always_declare_return_types in the file level
https://dart-lang.github.io/linter/lints/always_declare_return_types.html
![image](https://user-images.githubusercontent.com/1186833/103107707-20ad9f00-4641-11eb-85f7-9ffc2c415d71.png)

**Comment by lzoran** [comment]
Hi @absar,

Thanks for the feedback.

The `messages*.dart` files are generated by the [intl_translation](https://github.com/dart-lang/intl_translation) package on which the plugin relies on. Unfortunately, we will need to wait until they fix it.

**Comment by absar** [comment]
Thank you for the quick update, ok hope Googlers will soon fix the issue.
Found an intl_translation issue raised in Aug-2020, hope it will be merged soon: https://github.com/dart-lang/intl_translation/pull/112

**Comment by lzoran** [comment]
Hi @absar,

The latest version of the Flutter Intl plugin (`1.14.0`) now generates missing return types for the projects that support null-safety (min environment sdk `>=2.12.0`).
