### ISSUE TITLE
Migrating to null safety

### ISSUE THREAD

**Issue by jimbengtsson92** [localizely/flutter-intl-intellij#64]
I am having issues when trying to migrate to null-safety. When running `dart migrate` I get the following output:
```
Analyzing project...
[----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------\]Bad state: Error: package has unmigrated dependencies.

Before migrating your package, we recommend ensuring that every library it
imports (either directly or indirectly) has been migrated to null safety, so
that you will be able to run your unit tests in sound null checking mode.  You
are currently importing the following non-null-safe libraries:

  package:dance_school/generated/intl/messages_all.dart
  package:dance_school/generated/intl/messages_en.dart
  package:dance_school/generated/intl/messages_sv.dart
  package:dance_school/generated/l10n.dart

Please upgrade the packages containing these libraries to null safe versions
before continuing.  To see what null safe package versions are available, run
the following command: `dart pub outdated --mode=null-safety`.
```

So the generated files from this package does not let me migrate. Does anyone know what to do to fix this?

I am using the latest version, 1.13.0-2019.2, which is supposed to have support for null-safety.

**Comment by lzoran** [comment]
Hi @jimbengtsson92,

Flutter Intl plugin checks `sdk` version within the `pubspec.yaml` file and generate localization files according to the set value.
Does updating the `sdk` min constraint work for you?

```
environment:
  sdk: ">=2.12.0-0 <3.0.0"
```

**Comment by lzoran** [comment]
> Analyzing project...
[---------------------------------- ...Error: package has unmigrated dependencies
- Maybe I'm missing something, but according to the message you've posted, it seems that you have some dependencies that do not support null-safety in your project. 

Could you check if all your dependencies support null-safety?

Also, could you check if you have the `dance_school` package as a dependency in you project (maybe you are using it as a dependency, and it is not migrated yet)?

**Comment by lzoran** [comment]
Hi @jimbengtsson92,

Sorry for the late reply.

Not sure if you have found a solution in the meantime.
If not, maybe generating null-safe localization code before running `dart migrate` could help.

```
cd dance_school
flutter pub global activate intl_utils 2.1.0
flutter pub global run intl_utils:generate
```

If the proposed solution does not work, could you provide us minimal reproducible sample app? 
I've tried several times to reproduce this issue on my machine but without success every time. :(

**Comment by jimbengtsson92** [comment]
Thanks for you replies @lzoran,

I managed to get around it by disabling the Flutter intl plugin in Android studio (to avoid generating new files). Then I deleted the `lib/generated` folder and commented out all places where the localization files were being used, e.g. `S.of(context).someText`. This way I was able to perform `dart migrate`.

I can try to create a small sample app where this problem occurs. My guess is that the generated files are caught by the `dart migrate` command and are flagged as a package not being migrated to null safety yet.

**Comment by d3xt3r2909** [comment]
> flutter pub global run intl_utils:generate

Noup. This is not fixing an issue. 

The thing is that for running `dart migrate` you need to have a version lower than 2.12 and for this plugin you need to have at least dart `2.12`

Is it anyhow possible to generate these files without putting dart version on 2.12? I hope that I will not ended by commenting all translation lines :D

**Comment by lzoran** [comment]
Hi @d3xt3r2909,

If you are using `Flutter ^2.0.0`, you can globally activate the `intl_utils ^2.0.0` and run the generation of localization files that are null-safe. In case you are using the Flutter Intl plugin, it is required to disable it during this process to avoid unwanted re-generation. 

Steps:

1. Temporarily disable the Flutter Intl IDE plugin (update the `pubspec.yaml` file)
```
flutter_intl:
  enabled: false
```

2. Globally activate the null-safe `intl_utils` package
```
flutter pub global activate intl_utils 2.4.0
```

3. Generate null-safe localization files
```
cd your_project
flutter pub global run intl_utils:generate
```

4. Enable previously disabled Flutter Intl IDE plugin after you finished your migration (`sdk: ">=2.12.0 <3.0.0"`)
```
flutter_intl:
  enabled: true
```

**Comment by d3xt3r2909** [comment]
This works. Thanks a lot. I believe that this is not issue anymore then..

**Comment by lzoran** [comment]
@d3xt3r2909 I'm glad it helped!

I am closing this issue now.
In case of any new problems, please open a new issue.

**Comment by jimbengtsson92** [comment]
For another project I used the migration tool even though it complained about some packages not been migrated to null safety, and that went perfectly fine.
