### ISSUE TITLE
Run dartfmt on the generated dart code

### ISSUE THREAD

**Issue by britannio** [localizely/flutter-intl-intellij#65]
Otherwise the generated code will change the next time the plugin runs if `flutter format` was run beforehand despite no changes other than whitespace being made.

**Comment by lzoran** [comment]
Hi @britannio,

Sorry for the late reply.

The latest version of the Flutter Intl plugin (`1.14.0`) now generates formatted code for the projects that support null-safety (min environment sdk `>=2.12.0`). 

I've tested running the `flutter format .` on all flutter channels, and it works well (no changes). Only on the `stable` channel formatting may be different for the ICU Select messages, but I guess that it will be solved with the next or one of the upcoming releases.

Does that solve your issue?

**Comment by lzoran** [comment]
I'm closing this issue as new versions of the Flutter Intl plugin generate formatted code.
In case you detect any diff in formatting, please feel free to open a new issue.
