### ISSUE TITLE
The menu of "Flutter Intl" doesn't display.

### ISSUE THREAD

**Issue by YowFung** [localizely/flutter-intl-intellij#67]
I was installed this plugin, but the menu doesn't display in my Android Studio.

![image](https://user-images.githubusercontent.com/26346560/117140258-c89d5b00-addf-11eb-8fb7-938f1699f03b.png)

![image](https://user-images.githubusercontent.com/26346560/117140374-ee2a6480-addf-11eb-849a-d2f1e808a734.png)

**Comment by lzoran** [comment]
Hi @YowFung,

Thanks for reporting this!

According to the posted images, the issue might be in the project structure (opened directory is not the root of the Flutter app). 
It seems that the `Flutter` plugin menu is not available here also.

Could you check if everything works well if you open just the `visualm` directory in your IDE?

**Comment by YowFung** [comment]
@lzoran Just as you said, it's resolved. Thank you!

**Comment by hellomentorplus** [comment]
![Screen Shot 2022-10-28 at 5 59 35 pm](https://user-images.githubusercontent.com/110004234/198523839-7e62f32b-9211-47e3-a2f2-f9b7edef85be.png)

I open the project from root, `Flutter` plugin menu is available, but `Flutter Intl` is not. Any idea?

**Comment by lzoran** [comment]
Hi @hellomentorplus,

Not sure what might be the issue. :/

Could you check if you can see the `Flutter Intl` menu for the [sample app](https://github.com/localizely/flutter-intl-plugin-sample-app)?

Also, could you share more details regarding your setup, so we can try to reproduce this issue (IDE version, Flutter version, Flutter Intl plugin version, project structure, reproducible example)?
