### ISSUE TITLE
How to support different regions of the same language at the same time? 

### ISSUE THREAD

**Issue by lizhuoyuan** [localizely/flutter-intl-intellij#68]
https://github.com/dart-lang/intl/issues/386

I have "intl_zh.arb" file, I hope this will be automatically loaded when the phone's locale is zh_HK, zh_CN.
Now,`AppLocalizationDelegate().isSupported(Locale('zh_HK'))` return false.

**Comment by lzoran** [comment]
Hi @lizhuoyuan,

As I can remember, this should work.
I think that you are passing incorrectly formatted locale to the `isSupported` method. Instead of `Locale('zh_HK')`, you should use `Locale('zh', 'HK')`.
