### ISSUE TITLE
Make generated code safer and compatible with implicit-dynamic:false

### ISSUE THREAD

**Issue by knaeckeKami** [localizely/flutter-intl-intellij#7]
Currently, if one used plurals, methods like this are generated:

```dart
  String my_plural(dynamic howMany) {
    return Intl.plural(
      howMany,
      zero: '...',
      one: '...',
      other: '...',
      name: 'my_plural',
      desc: '',
      args: [howMany],
    );
  }
```
The parameter is dynamic, but Intl.plural only accepts a num. It's easy to accidentially pass a string into the method, which would compile fine only to fail at runtime. 

Additionally, if the user uses `implicit-dynamic: false`, this is actually an error for the analyzer:

https://imgur.com/a/xn8NZcE

**Comment by aleksakrstic** [comment]
Hi @knaeckeKami, thanks for this feedback.

Will consider this for one of upcoming extension updates.

**Comment by aleksakrstic** [comment]
@knaeckeKami 
This is released with plugin version `1.4.1`.

**Comment by maguro** [comment]
It doesn't seem to be fixed:

    static m1(a) => "${Intl.plural(a, one: 'un carácter', other: '${a} caracteres')}";

**Comment by knaeckeKami** [comment]
Youre right.
It's still not fixed for the m<number> functions and for the initialmessages function

**Comment by aleksakrstic** [comment]
Hi @maguro @knaeckeKami 
The code inside `messages_*.dart` files is generated by Dart's `intl_translation` library, on which this plugin depends, and does not have influence to change it.
Once it is updated by the team that works on `intl_translation`, we would willingly update the version this plugin depends on.

**Comment by sydneyagcaoili** [comment]
Any updates on this?

**Comment by lzoran** [comment]
Hi @sydneyagcaoili,

Does excluding generated files from analysis work for you?

The `analysis_options.yaml` file:
```
analyzer:
  exclude: [lib/generated/**]
  strong-mode:
    implicit-casts: false
```

**Comment by sydneyagcaoili** [comment]
> Hi @sydneyagcaoili,
> 
> Does excluding generated files from analysis work for you?
> 
> The `analysis_options.yaml` file:
> 
> ```
> analyzer:
>   exclude: [lib/generated/**]
>   strong-mode:
>     implicit-casts: false
> ```

I actually did exclude the whole file but it's nice to know about strong-mode thank you!
