### ISSUE TITLE
Parameter with curly braces is not recognised if preceded by a less-than sign in a NNBD project

### ISSUE THREAD

**Issue by jsroest** [localizely/flutter-intl-intellij#70]
If this is in an .arb file
 "validatorInputTooSmallExclusive": "Invoer te klein (< {minLength})",

The generated code is:
  /// `Invoer te klein (< {minLength})`
  String get validatorInputTooSmallExclusive {
    return Intl.message(
      'Invoer te klein (< {minLength})',
      name: 'validatorInputTooSmallExclusive',
      desc: '',
      args: [],
    );
  }

if this is in an .arb file:
"validatorInputToLargeExclusive": "Invoer te groot (> {maxLength})",

The generated code is:
  /// `Invoer te groot (> {maxLength})`
  String validatorInputToLargeExclusive(Object maxLength) {
    return Intl.message(
      'Invoer te groot (> $maxLength)',
      name: 'validatorInputToLargeExclusive',
      desc: '',
      args: [maxLength],
    );
  }

The less-than sign causes the parameter to be omitted from the generated code.

This is version 1.14.0-2019.2 of the plugin, in a NNBD project. This does not happen when the project is not NNBD.

**Comment by S4b3** [comment]
Hello, I found this issue while looking for the exact same problem. 

I'm externalizing enriched text with xml tags, and if in the text is present an "opening" curly brace anywhere in the string, the rest of the string is not going to be processed and therefore included in the generated getter.

Example: 

```json 
"profilePageContentSubscriptionDate": "Data di iscrizione: <b>{date}</b>",
    "@profilePageContentSubscriptionDate": {
        "description": "A message that shows when the user subscription date by receiving it as a param",
        "placeholders": {
            "date": {
                "type": "String",
                "example": "20/02/2020"
            }
        }
    }
```
Generates: 
```dart
/// `Data di iscrizione: <b>{date}</b>`
  String profilePageContentSubscriptionDate(Object date) {
    return Intl.message(
      'Data di iscrizione: ',
      name: 'profilePageContentSubscriptionDate',
      desc:
          'A message that shows when the user subscription date by receiving it as a param',
      args: [date],
    );
  }
}
```

To me, this makes the plugin pretty much unusable and therefore requires major attention.

**Comment by lzoran** [comment]
Hi @jsroest, @S4b3,

The issue with tags within translations is fixed with the latest version of the Flutter Intl plugin (1.15.0).

**Comment by aleksakrstic** [comment]
I am closing this issue now.
In case of any new problems, please open a new issue.
