### ISSUE TITLE
Error parsing keys that contain correctly escaped json

### ISSUE THREAD

**Issue by kristijorgji** [localizely/flutter-intl-intellij#71]
.arb file

```
{
// other keys being parsed fine, then this one failing
  "secret_key": "{\"blabla\":{\"title\":\"Pëdkjkj\"},\"somethingelse\":{\"title\":\"3 i ri\"},\"fd\":{\"title\":\"343 i 2\"},\"df\":{\"title\":\"Pëlf fl\"},\"fdkj\":{\"title\":\"Përdinj\",\"desc\":\"Ju doet e dhëna\"}}",
"locales": "{\"de\":\"German\",\"it\":\"Italian\"}",
}
```

The intellij plugin then gives error

```
ERROR: The 'secret_key' key will be ignored due to parsing errors.
ERROR: The 'locales' key will be ignored due to parsing errors.
```

And does not add in generated `l10n.dart` those 2 keys, and we have to manually add always before commit...

But the other command `flutter pub run intl_utils:generate` works correctly when generating _de.arb _it.arb and so on files, it parses correctly and adds this in dart code.

Looks like only this plugin is not correctly parsing the values (additionaly would be also great for more information of error then just parsing errors but i guess that is just a catch for a general error happening with a particular key)

**Comment by lzoran** [comment]
Closing this issue, as it's fixed with the latest version of the Flutter Intl plugin (`1.16.0`).
In case you detect any irregularity, please feel free to open a new issue.
