### ISSUE TITLE
Incompatibility with latest Android Studio version 

### ISSUE THREAD

**Issue by JasurbekA** [localizely/flutter-intl-intellij#72]
Hello contributors 
I wanted to install the plugin but got this error

`Plugin "Flutter Intl" was not installed: Downloaded version is incompatible with the current IDE: Plugin 'Flutter Intl' (version '1.15.0-2019.2') is not compatible with the current version of the IDE, because it requires build 203.4203.26 or older but the current build is AI-203.7717.56 `

When are planning to release compatible version of the plugin with latest version of Android

PS. I am using Arctic Fox Android Studio, below I provide more info about IDEA
```
Android Studio Arctic Fox | 2020.3.1
Build #AI-203.7717.56.2031.7583922, built on July 27, 2021
Runtime version: 11.0.10+0-b96-7281165 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.5.2
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 12
Registry: ide.instant.shutdown=false, external.system.auto.import.disabled=true
Non-Bundled Plugins: Dart, io.flutter, org.jetbrains.kotlin, com.nbadal.ktlint
```

**Comment by lzoran** [comment]
Hi @JasurbekA,

Thanks for reporting this!

Not sure why Android Studio tried to install the `1.15.0-2019.2` version. I would expect to install the `1.15.0-2020.3` version for the Arctic Fox 2020.3.1. 😕 

In case you updated your Android Studio from the older version, could you check if IDE restart helps?

**Comment by JasurbekA** [comment]
@lzoran 
Thanks for quick response. 
But your suggestion did not help as well 😕

Any other suggestion ?

**Comment by JasurbekA** [comment]
@lzoran
Finally, Android Studio decided to download the stable version of the plugin
Issue is fixed

**Comment by lzoran** [comment]
Hi @JasurbekA,

Although we have closed this issue, could you share with us how you solved it? Did it require some additional config, or it just started working? 
I guess others may encounter the same problem, so it would be helpful if we could give them some hints. Also, we might be able to spot something that needs to be fixed on the plugin.

**Comment by JasurbekA** [comment]
Hi @lzoran 
Sure I can share
1. I updated the latest patch once again from scratch
2. Clearing the Gradle cache 

Then suddenly it started working out of the box. Not sure what had gone wrong at that time
