### ISSUE TITLE
[Question] Possibility to move flutter_intl config from pubspec.yaml to a separate file

### ISSUE THREAD

**Issue by absar** [localizely/flutter-intl-intellij#73]
Hi, Is it possible to move flutter_intl configuration from pubspec.yaml to a separate file. The problem with current approach is every time pubspec.yaml file is updated, flutter_intl regenerates output files changing file timestamp, even though there are no changes in arb files.

**Comment by aleksakrstic** [comment]
Hi @absar 
Could you give me more info about the issue?
What timestamp is changed? How do you spot it?

**Comment by absar** [comment]
I mean all the output files are regenerated even though there is no change in related ARB files, which means the generated files' last modified date time on disk is changed, it's not an issue for version control systems like Git, but cloud storage solutions like dropbox will pick these files as changed files.
That's why it would be nice to move flutter_intl configuration outside of pubspec.yaml to a separate file, so that every time pubspec.yaml file is updated flutter_intl will not regenerate output files.

**Comment by aleksakrstic** [comment]
@absar I see.
Although I am not sure many devs use DropBox for source code storage, but mainly just git or similar.
May I ask why do you use DropBox, just to get an idea of the use case?

**Comment by absar** [comment]
@aleksakrstic I did not say I use dropbox to store source code was trying to answer your question "_What timestamp is changed? How do you spot it?_" with a simple answer.
My use case is related to local NAS file versioning and then cloud backups, but that's not important here.
The actual issue/request is simple, can you move the config out of pubspec.yaml and don't re-generate output files if the ARB files are not changed, am I asking too much?

**Comment by aleksakrstic** [comment]
Using a separate config file sounds simple, but migrating existing users might not be.

I will leave this issue open to see if it gets upvotes. 
If somebody else faces the same issue, please comment your use case so we get the better understanding.

**Comment by aleksakrstic** [comment]
Closing this issue due to no upvotes

**Comment by long1eu** [comment]
now it has one :D

**Comment by SERDUN** [comment]
I also hope to understand how to bear it move flutter intl configuration from pubspec.yaml to a separate file. :)

**Comment by yurecKovalchuk** [comment]
It would be useful to have a separate configuration file.
