### ISSUE TITLE
Don't delegated S?? 

### ISSUE THREAD

**Issue by zsanzharko** [localizely/flutter-intl-intellij#78]
My problem with delegating S, but I wrote in code, like example in Getting Started **Localizely**

Adding in code
```
class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      localizationsDelegates: [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
        S.delegate
      ],
      supportedLocales: S.delegate.supportedLocales,
      onGenerateTitle: (BuildContext context) => "Zholdau",
      title: S.of(context).title,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: S.of(context).title),
    );
  }
}
```

intl_en.arb
```
{
  "title" : "Helo"
}
```

Error exeption
```
======== Exception caught by widgets library =======================================================
The following assertion was thrown building MyApp(dirty):
No instance of S present in the widget tree. Did you add S.delegate in localizationsDelegates?
'package:zholdau/generated/l10n.dart':
Failed assertion: line 44 pos 12: 'instance != null'
```

pubspec
```
Flutter
sdk: ">=2.15.1 <3.0.0"

flutter_intl:
  enabled: true

intl: ^0.17.0
```

**Comment by zsanzharko** [comment]
I did not find the problem on the Internet

**Comment by lzoran** [comment]
Hi @zsanzharko,

In order to use localized messages in `MyApp` widget you should:
-  Use `onGenerateTitle` callback for app's title 
- Wrap `MyHomePage` with the `Builder` widget

```
class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      localizationsDelegates: [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
        S.delegate
      ],
      supportedLocales: S.delegate.supportedLocales,
      onGenerateTitle: (BuildContext context) => S.of(context).title,
      // title: S.of(context).title, // Issue 1
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      // home: MyHomePage(title: S.of(context).title), // Issue 2
      home: Builder(
        builder: (BuildContext context) =>
            MyHomePage(title: S.of(context).title),
      ),
    );
  }
}
```

Hope it helps!

**Comment by zsanzharko** [comment]
Okay, I will try later

If you don't mind, can you explain why we wrap it in a Builder shell

**Comment by parcool** [comment]
> If you don't mind, can you explain why we wrap it in a Builder shell

why?

**Comment by fotechv** [comment]
> Okay, I will try later
> 
> If you don't mind, can you explain why we wrap it in a Builder shell

This error usually occurs when `MaterialApp `has not yet completed the initialization process of `localizationsDelegates`, but you have attempted to access the text strings in `S.of(context)` before they are ready. This is an issue related to the initialization order and the possibility that the localization strings have not been fully loaded before being used.

Explanation for those who come after :))

**Comment by lmarquar** [comment]
follow up on @lzoran, this is the current form which works and fixes this error:
`
              localizationsDelegates: const [
                S.delegate,
                ...AppLocalizations.localizationsDelegates,
              ],
`
