### ISSUE TITLE
Kazakh lang with Latin alphabet

### ISSUE THREAD

**Issue by zsanzharko** [localizely/flutter-intl-intellij#79]
Hello! At the moment, Kazakhstan is switching to the Latin alphabet, and before it was in Cyrillic. In 2017, the President of the Republic of Kazakhstan signed the Decree “On the transfer of the Kazakh language alphabet from Cyrillic to Latin script”. Can you pay attention to it.

I would like to add additionally the Kazakh language in the form of the Latin alphabet, leaving the Cyrillic alphabet. This will help applications to gradually move from one view to another.

**Comment by zsanzharko** [comment]
[https://tengrinews.kz/userdata/images/u289/2658b3c88e6635b51d5c230163dbb89f.jpg](url)

**Comment by zsanzharko** [comment]
![2658b3c88e6635b51d5c230163dbb89f](https://user-images.githubusercontent.com/57348097/151687825-929b7337-1f94-4216-98d8-1bd5cfcece1b.jpg)

**Comment by aleksakrstic** [comment]
Hi @zsanzharko 
What issues do you have with Kazakh lang and its usage with Flutter Intl plugin?

**Comment by aleksakrstic** [comment]
Closing this issue due to no response
