### ISSUE TITLE
Generated code doesn't notify widgets that depend on it about changes, like an InheritedWidget

### ISSUE THREAD

**Issue by IoanaAlexandru** [localizely/flutter-intl-intellij#8]
I believe localization should work like an InheritedWidget, meaning the localization resource should notify the widgets that depend on it if the locale changes.

I have a simple app with a BottomNavigationBar and an AppBar which has a 'Settings' action. Now in the Settings page, I can change the theme (using the `dynamic_theme` package) and the language (calling `S.load(...)`). When I change the theme and then press back on the settings page, the previous page also changed its theme. However, if I change the language, I have to call `setState()` (or tap an item in the navigation bar, in my case) for the language to update.

Is there any workaround for this?

**Comment by aleksakrstic** [comment]
Hi @IoanaAlexandru 

I am not sure `setState()` should be automatically called around `S.load(...)` (by the plugin), in order to have better control over setting the state.
If that is something that constantly repeats, it can be wrapped in a function like:

    void setLocale(Locale newLocale) {
        setState(() {
          S.load(newLocale);
        });
    }

Does that sound ok in your case?

**Comment by IoanaAlexandru** [comment]
The problem is that `setState()` I can only call directly on the page I actually trigger `S.load` on (i.e. the settings page, in my case). For my app, when I press back (`Navigator.pop`) to go back to the main page, the main page is not aware that the locale changed until I press a button to force it to build again. Does that make sense?

**Comment by EdwynZN** [comment]
I experience a similar problem when using the showLicensePage() widget, inside its body it uses Localization.override(locale: const Locale('en, 'US') child: ...) so the licenses are in english, but when I pop that PageRoute all my app is in English too, if I check S.localeName it has a different locale depending on what language my device is (and its supported by my ARB files) but the app is still in English and a hot reload or changing the language device do nothing, I have to close and reopen the app

**Comment by aleksakrstic** [comment]
@IoanaAlexandru 
Is `localizationDelegates` set at the **root** of your application like it is in this sample: https://github.com/localizely/flutter-intl-plugin-sample-app/blob/master/lib/main.dart ?

**Comment by aleksakrstic** [comment]
Hi @IoanaAlexandru 
Following sample project (uses `Navigator`) https://github.com/nisrulz/flutter-examples/tree/master/handling_routes
when extended with localization from the plugin works ok in that manner.
For instance, `localizationsDelegates` is set in `main.dart` and `S.load` is called inside `AboutPage` (the page needed to be transformed into `StatefulWidget` in order to call `setState` around it).

Selected locale is kept after page is switched.

Could you check if such an example could be applied for your project?
