### ISSUE TITLE
"Too large" warnings

### ISSUE THREAD

**Issue by dpedrinha** [localizely/flutter-intl-intellij#80]
So I've recently updated some plugins and now I'm getting the following warnings:

> Warning: numberFormatSymbols from package:intl/number_symbols_data.dart is too large. Some optimizations have been disabled, and the compiler might run out of memory. Consider refactoring this code into smaller components.
Warning: numberFormatSymbols from package:intl/number_symbols_data.dart is too large. Some optimizations have been disabled, and the compiler might run out of memory. Consider refactoring this code into smaller components.
Warning: numberFormatSymbols from package:intl/number_symbols_data.dart is too large. Some optimizations have been disabled, and the compiler might run out of memory. Consider refactoring this code into smaller components.
Warning: getMaterialTranslation from package:flutter_localizations/src/l10n/generated_material_localizations.dart is too large. Some optimizations have been disabled, and the compiler might run out of memory. Consider refactoring this code into smaller components.
Warning: getCupertinoTranslation from package:flutter_localizations/src/l10n/generated_cupertino_localizations.dart is too large. Some optimizations have been disabled, and the compiler might run out of memory. Consider refactoring this code into smaller components.
Warning: getMaterialTranslation from package:flutter_localizations/src/l10n/generated_material_localizations.dart is too large. Some optimizations have been disabled, and the compiler might run out of memory. Consider refactoring this code into smaller components.
Warning: getMaterialTranslation from package:flutter_localizations/src/l10n/generated_material_localizations.dart is too large. Some optimizations have been disabled, and the compiler might run out of memory. Consider refactoring this code into smaller components.
Warning: getCupertinoTranslation from package:flutter_localizations/src/l10n/generated_cupertino_localizations.dart is too large. Some optimizations have been disabled, and the compiler might run out of memory. Consider refactoring this code into smaller components.
Warning: getCupertinoTranslation from package:flutter_localizations/src/l10n/generated_cupertino_localizations.dart is too large. Some optimizations have been disabled, and the compiler might run out of memory. Consider refactoring this code into smaller components.

I'm guessing it's coming from this plugin.

**Comment by lzoran** [comment]
Hi @dpedrinha,

The Flutter Intl plugin only generates the localization files. By default, those files are placed in the `lib/generated` folder. However, the attached warnings do not mention those files but the `intl` and `flutter_localizations` packages on which the generated code relies. Thus, I'm not sure if that has anything with this plugin. 😕

**Comment by dpedrinha** [comment]
Ok. I'll forward the issue to them then.

TY.
