### ISSUE TITLE
Free plan should have a limited number of requests pr day/week/month, to make localizely actual usable after trial

### ISSUE THREAD

**Issue by large** [localizely/flutter-intl-intellij#83]
I tested the product and it worked fine, sleek integration and comfortable download function.
After "trial" period it is rather useless, since the API are blocked:

> ERROR: Failed to download data from Localizely.
> {"errorCode":"forbidden","errorMessage":"API usage is not available for Free account plans. Consider upgrading project owner's account plan.","errorData":null}

As a personal developer $19 a month or $192 a year is to stiff and I am fine paying for translation-services, not for api-access.

---
When a person is blocked, then that person gets creative.
Setting up the l10n and let Flutter generate files, gave me the same result as your plugin.
Alternative interface Weblate and Github as storage gave me the same interface + download-functionality.

**Comment by aleksakrstic** [comment]
Hi @large 
Thanks for the feedback!
Personal plans are mainly used by developers and still one of the cheapest.
We tried to make it fit the needs for the most of developers, but if that is not the case for you, I understand and sorry for that.
