### ISSUE TITLE
Multiple placeholders in plural forms

### ISSUE THREAD

**Issue by deakjahn** [localizely/flutter-intl-intellij#90]
I couldn't find any solution to a fairly common problem: multiple placeholders of plural forms. Both the following:

    "countSelectedPhotos2": "{howMany, plural, zero{0/{total} selected photo} one{1/{total} selected photo} other{{howMany}/{total} selected photos}}",
    "countSelectedPhotos3": "{howMany, total, plural, zero{0/{total} selected photo} one{1/{total} selected photo} other{{howMany}/{total} selected photos}}",

 generate a seemingly correct function (although with the order of placholders reversed)

    /// `{howMany, plural, zero{0/{total} selected photo} one{1/{total} selected photo} other{{howMany}/{total} selected photos}}`
    String countSelectedPhotos2(Object total, Object howMany) {
      return Intl.message(
        '{howMany, plural, zero{0/$total selected photo} one{1/$total selected photo} other{$howMany/$total selected photos}}',
        name: 'countSelectedPhotos2',
        desc: '',
        args: [total, howMany],
      );
    }
  
    /// `{howMany, total, plural, zero{0/{total} selected photo} one{1/{total} selected photo} other{{howMany}/{total} selected photos}}`
    String countSelectedPhotos3(Object total, Object howMany) {
      return Intl.message(
        '{howMany, total, plural, zero{0/$total selected photo} one{1/$total selected photo} other{$howMany/$total selected photos}}',
        name: 'countSelectedPhotos3',
        desc: '',
        args: [total, howMany],
      );
    }

but they don't work in practice, instead of the pluralized version, I receive the whole definition string in the running app.

The test functions in `int:test\message_format_test.dart` (testSimplePlural, testSimplePluralNoOffset) seem to suggest that it is supported by the underlying mechanism.

**Comment by lzoran** [comment]
Hi @deakjahn,

I've tested posted messages, and it seems that the `countSelectedPhotos2` has valid output.

```
/// `{howMany, plural, zero{0/{total} selected photo} one{1/{total} selected photo} other{{howMany}/{total} selected photos}}`
String countSelectedPhotos2(num howMany, Object total) {
  return Intl.plural(
    howMany,
    zero: '0/$total selected photo',
    one: '1/$total selected photo',
    other: '$howMany/$total selected photos',
    name: 'countSelectedPhotos2',
    desc: '',
    args: [howMany, total],
  );
}
```

Regarding the `countSelectedPhotos3` message, I'm not sure if that is valid ICU plural syntax. 😕 

Also, if you want to specify the order and type of the arguments in the generated localization method, you just need to add message metadata in arb files.

```
"countSelectedPhotos2": "{howMany, plural, zero{0/{total} selected photo} one{1/{total} selected photo} other{{howMany}/{total} selected photos}}",
"@countSelectedPhotos2": {
  "placeholders": {
    "howMany": {
      "type": "num"
    },
    "total": {
      "type": "num"
    }
  }
},
```

```
/// `{howMany, plural, zero{0/{total} selected photo} one{1/{total} selected photo} other{{howMany}/{total} selected photos}}`
String countSelectedPhotos2(num howMany, num total) {
  return Intl.plural(
    howMany,
    zero: '0/$total selected photo',
    one: '1/$total selected photo',
    other: '$howMany/$total selected photos',
    name: 'countSelectedPhotos2',
    desc: '',
    args: [howMany, total],
  );
}
```

**Comment by deakjahn** [comment]
Yep, I just wanted to answer myself that, after many repeated attempts, now I get an `Intl.plural()` and that's the correct one. The string I finally have is:

    "countSelectedPhotos": "{howMany, plural, zero{0/{total} selected photo} one{1/{total} selected photo} other{{howMany}/{total} selected photos}}"

and (apart from removing the 2 at the end of the key because I actually only need one if it works), I can't see any difference to the one I started the post with. So, I don't know why it started to work but it does now. :-)
