### ISSUE TITLE
Linux Platform

### ISSUE THREAD

**Issue by DongPhamBK** [localizely/flutter-intl-intellij#92]
Can the plugin help me create multi-language apps on Linux platform? I want to develop my application on Linux platform in the future.

**Comment by lzoran** [comment]
The Flutter Intl plugin generates boilerplate localization code for the [intl](https://pub.dev/packages/intl) package.  
You should be able to use the Flutter Intl plugin on all platforms that your IDE runs on (Windows, macOS, Linux).
Also, the Flutter Intl plugin generates localization code for the Flutter apps, and thus it should work on all Flutter platforms (Android, iOS, Windows, macOS, Linux, and web).

To check how Flutter Intl works, you can clone the [Flutter Intl plugin sample app](https://github.com/localizely/flutter-intl-plugin-sample-app) and run it on the Linux platform.

Hope I helped!
